"""SQLAlchemy ORM models.

Schema conventions
------------------
* All timestamps are stored **timezone-aware in UTC**. The clinic's local
  timezone is a presentation concern handled in ``app.services.slots``.
* Enum-like columns are ``String`` + a Python ``StrEnum`` rather than a native
  database ENUM. Native enums require a migration to add a value; strings do
  not, and the constraint is expressed with ``CheckConstraint`` so the database
  still rejects garbage.
* Anything that talks to a third party (email, calendar) is persisted as an
  *outbox row* first and delivered by a background worker. The request path
  never depends on a third party being up.
"""

from __future__ import annotations

import enum
from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    Time,
    UniqueConstraint,
    text,
)
from sqlalchemy.types import TypeDecorator
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class UTCDateTime(TypeDecorator):
    """A timestamp column that is *always* timezone-aware UTC in Python.

    Postgres stores ``timestamptz`` and hands back aware datetimes; SQLite has
    no timezone type and hands back **naive** ones. Without this decorator every
    comparison against :func:`utcnow` would raise
    ``can't compare offset-naive and offset-aware datetimes`` on SQLite while
    working fine on Postgres — the worst kind of bug, one that only appears on
    the other environment.

    So normalisation happens once, at the type boundary: everything is
    converted to UTC on the way in, and re-attached to UTC on the way out.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect):
        if value is None:
            return None
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)

    def process_result_value(self, value: datetime | None, dialect):
        if value is None:
            return None
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)


# --------------------------------------------------------------------------
# Enumerations
# --------------------------------------------------------------------------
class Role(enum.StrEnum):
    PATIENT = "patient"
    DOCTOR = "doctor"
    ADMIN = "admin"


class AppointmentStatus(enum.StrEnum):
    HELD = "held"              # slot reserved, symptom form pending
    CONFIRMED = "confirmed"    # booked
    COMPLETED = "completed"    # visit done, notes filed
    CANCELLED = "cancelled"    # cancelled by patient/doctor/admin
    EXPIRED = "expired"        # hold timed out without confirmation
    NO_SHOW = "no_show"


#: Statuses that occupy a slot. The partial unique index below is built on this
#: set — it is the single source of truth for "is this slot taken?".
BLOCKING_STATUSES: tuple[str, ...] = (AppointmentStatus.HELD, AppointmentStatus.CONFIRMED)
_BLOCKING_SQL = "status IN ('held','confirmed')"


class CancelActor(enum.StrEnum):
    PATIENT = "patient"
    DOCTOR = "doctor"
    ADMIN = "admin"
    SYSTEM_LEAVE = "system_leave"
    SYSTEM_HOLD_EXPIRY = "system_hold_expiry"


class Urgency(enum.StrEnum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"


class AISource(enum.StrEnum):
    LLM = "llm"            # generated by the model
    FALLBACK = "fallback"  # deterministic rule-based degradation
    PENDING = "pending"


class JobStatus(enum.StrEnum):
    PENDING = "pending"
    SENT = "sent"
    FAILED = "failed"      # retryable, will be picked up again
    DEAD = "dead"          # exhausted max attempts, needs a human
    CANCELLED = "cancelled"


class Frequency(enum.StrEnum):
    """Standard prescription frequencies (Latin abbreviations used on scripts)."""

    OD = "OD"      # once daily
    BD = "BD"      # twice daily
    TDS = "TDS"    # three times daily
    QID = "QID"    # four times daily
    QHS = "QHS"    # at bedtime
    SOS = "SOS"    # as needed (no reminders scheduled)


#: Local clock times each frequency maps to when materialising reminders.
FREQUENCY_TIMES: dict[str, tuple[str, ...]] = {
    Frequency.OD: ("09:00",),
    Frequency.BD: ("09:00", "21:00"),
    Frequency.TDS: ("08:00", "14:00", "20:00"),
    Frequency.QID: ("08:00", "12:00", "16:00", "20:00"),
    Frequency.QHS: ("22:00",),
    Frequency.SOS: (),
}


# --------------------------------------------------------------------------
# Identity
# --------------------------------------------------------------------------
class User(Base):
    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint("role IN ('patient','doctor','admin')", name="ck_users_role"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    full_name: Mapped[str] = mapped_column(String(160), nullable=False)
    phone: Mapped[str | None] = mapped_column(String(32))
    date_of_birth: Mapped[datetime | None] = mapped_column(Date)
    gender: Mapped[str | None] = mapped_column(String(24))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, onupdate=utcnow, nullable=False)

    doctor_profile: Mapped["DoctorProfile | None"] = relationship(
        back_populates="user", uselist=False, cascade="all, delete-orphan"
    )
    calendar_account: Mapped["CalendarAccount | None"] = relationship(
        back_populates="user", uselist=False, cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<User {self.id} {self.role} {self.email}>"


# --------------------------------------------------------------------------
# Doctor configuration
# --------------------------------------------------------------------------
class DoctorProfile(Base):
    __tablename__ = "doctor_profiles"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False)
    specialisation: Mapped[str] = mapped_column(String(120), nullable=False, index=True)
    qualifications: Mapped[str | None] = mapped_column(String(255))
    bio: Mapped[str | None] = mapped_column(Text)
    experience_years: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    consultation_fee: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    #: Length of one appointment, in minutes. Slot grid is derived from this.
    slot_duration_minutes: Mapped[int] = mapped_column(Integer, default=30, nullable=False)
    #: Gap left after each appointment (cleaning/notes). Part of the grid step.
    buffer_minutes: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    room: Mapped[str | None] = mapped_column(String(64))
    is_accepting_patients: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, onupdate=utcnow, nullable=False)

    user: Mapped[User] = relationship(back_populates="doctor_profile")
    working_hours: Mapped[list["DoctorWorkingHour"]] = relationship(
        back_populates="doctor", cascade="all, delete-orphan", order_by="DoctorWorkingHour.weekday"
    )
    leaves: Mapped[list["DoctorLeave"]] = relationship(
        back_populates="doctor", cascade="all, delete-orphan", order_by="DoctorLeave.leave_date"
    )

    __table_args__ = (
        CheckConstraint("slot_duration_minutes BETWEEN 5 AND 240", name="ck_doctor_slot_len"),
        CheckConstraint("buffer_minutes BETWEEN 0 AND 120", name="ck_doctor_buffer"),
    )

    @property
    def slot_step_minutes(self) -> int:
        return self.slot_duration_minutes + self.buffer_minutes


class DoctorWorkingHour(Base):
    """One contiguous availability window on one weekday.

    Multiple rows per weekday are allowed, which is how split shifts
    (10:00–13:00 and 17:00–20:00) are represented.
    """

    __tablename__ = "doctor_working_hours"
    __table_args__ = (
        UniqueConstraint("doctor_id", "weekday", "start_time", name="uq_working_hour_window"),
        CheckConstraint("weekday BETWEEN 0 AND 6", name="ck_working_hour_weekday"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    doctor_id: Mapped[int] = mapped_column(ForeignKey("doctor_profiles.id", ondelete="CASCADE"), nullable=False, index=True)
    #: 0 = Monday … 6 = Sunday (matches ``date.weekday()``).
    weekday: Mapped[int] = mapped_column(Integer, nullable=False)
    start_time: Mapped[datetime] = mapped_column(Time, nullable=False)
    end_time: Mapped[datetime] = mapped_column(Time, nullable=False)

    doctor: Mapped[DoctorProfile] = relationship(back_populates="working_hours")


class DoctorLeave(Base):
    """A full-day leave. Uniqueness stops the same day being marked twice."""

    __tablename__ = "doctor_leaves"
    __table_args__ = (UniqueConstraint("doctor_id", "leave_date", name="uq_doctor_leave_day"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    doctor_id: Mapped[int] = mapped_column(ForeignKey("doctor_profiles.id", ondelete="CASCADE"), nullable=False, index=True)
    leave_date: Mapped[datetime] = mapped_column(Date, nullable=False, index=True)
    reason: Mapped[str | None] = mapped_column(String(255))
    created_by_user_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    #: How many confirmed appointments were auto-cancelled when this was applied.
    affected_appointment_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)

    doctor: Mapped[DoctorProfile] = relationship(back_populates="leaves")


# --------------------------------------------------------------------------
# Appointments
# --------------------------------------------------------------------------
class Appointment(Base):
    """A single booked slot.

    **Double-booking prevention lives here**, in ``uq_active_doctor_slot``: a
    *partial* unique index over ``(doctor_id, start_at)`` restricted to the
    blocking statuses. Two concurrent transactions inserting the same slot
    cannot both succeed — the loser gets an ``IntegrityError`` which the router
    translates into ``409 SLOT_TAKEN``. Cancelled/expired rows fall out of the
    index, so a released slot becomes bookable again with no cleanup.
    """

    __tablename__ = "appointments"
    __table_args__ = (
        Index(
            "uq_active_doctor_slot",
            "doctor_id",
            "start_at",
            unique=True,
            sqlite_where=text(_BLOCKING_SQL),
            postgresql_where=text(_BLOCKING_SQL),
        ),
        Index("ix_appointments_doctor_window", "doctor_id", "start_at"),
        Index("ix_appointments_patient_window", "patient_id", "start_at"),
        Index("ix_appointments_status_start", "status", "start_at"),
        CheckConstraint(
            "status IN ('held','confirmed','completed','cancelled','expired','no_show')",
            name="ck_appointment_status",
        ),
        CheckConstraint("end_at > start_at", name="ck_appointment_time_order"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    #: Human-friendly reference shown in emails/UI, e.g. ``APT-7K3QD2``.
    reference: Mapped[str] = mapped_column(String(16), unique=True, nullable=False, index=True)
    doctor_id: Mapped[int] = mapped_column(ForeignKey("doctor_profiles.id", ondelete="CASCADE"), nullable=False)
    patient_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)

    start_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)
    end_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default=AppointmentStatus.HELD)

    #: While ``status == 'held'`` the slot is reserved until this instant.
    hold_expires_at: Mapped[datetime | None] = mapped_column(UTCDateTime(), index=True)
    confirmed_at: Mapped[datetime | None] = mapped_column(UTCDateTime())

    reason_for_visit: Mapped[str | None] = mapped_column(String(255))
    mode: Mapped[str] = mapped_column(String(16), default="in_person", nullable=False)

    cancelled_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    cancelled_by: Mapped[str | None] = mapped_column(String(24))
    cancellation_reason: Mapped[str | None] = mapped_column(String(255))

    #: Set when a booking is moved; points at the slot it came from (audit trail).
    rescheduled_from_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    reschedule_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    #: Google Calendar event ids, one per attendee calendar.
    patient_calendar_event_id: Mapped[str | None] = mapped_column(String(255))
    doctor_calendar_event_id: Mapped[str | None] = mapped_column(String(255))

    reminder_sent_at: Mapped[datetime | None] = mapped_column(UTCDateTime())

    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, onupdate=utcnow, nullable=False)

    doctor: Mapped[DoctorProfile] = relationship()
    patient: Mapped[User] = relationship()
    symptom_report: Mapped["SymptomReport | None"] = relationship(
        back_populates="appointment", uselist=False, cascade="all, delete-orphan"
    )
    previsit_summary: Mapped["PreVisitSummary | None"] = relationship(
        back_populates="appointment", uselist=False, cascade="all, delete-orphan"
    )
    consultation: Mapped["Consultation | None"] = relationship(
        back_populates="appointment", uselist=False, cascade="all, delete-orphan"
    )

    @property
    def is_active(self) -> bool:
        return self.status in BLOCKING_STATUSES


# --------------------------------------------------------------------------
# Clinical content + AI artefacts
# --------------------------------------------------------------------------
class SymptomReport(Base):
    """Structured intake form the patient completes before confirming."""

    __tablename__ = "symptom_reports"

    id: Mapped[int] = mapped_column(primary_key=True)
    appointment_id: Mapped[int] = mapped_column(
        ForeignKey("appointments.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    symptoms: Mapped[str] = mapped_column(Text, nullable=False)
    duration_days: Mapped[int | None] = mapped_column(Integer)
    severity: Mapped[int | None] = mapped_column(Integer)  # 1-10 self-reported
    existing_conditions: Mapped[str | None] = mapped_column(Text)
    current_medications: Mapped[str | None] = mapped_column(Text)
    allergies: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)

    appointment: Mapped[Appointment] = relationship(back_populates="symptom_report")

    __table_args__ = (CheckConstraint("severity IS NULL OR severity BETWEEN 1 AND 10", name="ck_symptom_severity"),)


class AIArtifactMixin:
    """Provenance columns shared by both LLM outputs.

    Storing ``source``/``model``/``error`` next to the text is what makes the
    graceful-degradation story auditable: a reviewer can see exactly which
    summaries came from the model and which from the deterministic fallback.
    """

    source: Mapped[str] = mapped_column(String(16), default=AISource.LLM, nullable=False)
    model: Mapped[str | None] = mapped_column(String(80))
    prompt_version: Mapped[str | None] = mapped_column(String(24))
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    attempts: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    error: Mapped[str | None] = mapped_column(Text)
    raw_response: Mapped[str | None] = mapped_column(Text)


class PreVisitSummary(Base, AIArtifactMixin):
    """LLM triage note produced from the symptom form, shown to the doctor."""

    __tablename__ = "previsit_summaries"
    __table_args__ = (CheckConstraint("urgency IN ('Low','Medium','High')", name="ck_previsit_urgency"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    appointment_id: Mapped[int] = mapped_column(
        ForeignKey("appointments.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    urgency: Mapped[str] = mapped_column(String(8), nullable=False, default=Urgency.MEDIUM)
    chief_complaint: Mapped[str] = mapped_column(String(500), nullable=False)
    suggested_questions: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    red_flags: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    summary_note: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)

    appointment: Mapped[Appointment] = relationship(back_populates="previsit_summary")


class Consultation(Base):
    """Doctor's record of the visit."""

    __tablename__ = "consultations"

    id: Mapped[int] = mapped_column(primary_key=True)
    appointment_id: Mapped[int] = mapped_column(
        ForeignKey("appointments.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    doctor_id: Mapped[int] = mapped_column(ForeignKey("doctor_profiles.id", ondelete="CASCADE"), nullable=False)
    clinical_notes: Mapped[str] = mapped_column(Text, nullable=False)
    diagnosis: Mapped[str | None] = mapped_column(String(255))
    follow_up_date: Mapped[datetime | None] = mapped_column(Date)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, onupdate=utcnow, nullable=False)

    appointment: Mapped[Appointment] = relationship(back_populates="consultation")
    prescription: Mapped["Prescription | None"] = relationship(
        back_populates="consultation", uselist=False, cascade="all, delete-orphan"
    )
    postvisit_summary: Mapped["PostVisitSummary | None"] = relationship(
        back_populates="consultation", uselist=False, cascade="all, delete-orphan"
    )


class PostVisitSummary(Base, AIArtifactMixin):
    """Plain-language rewrite of the clinical notes, shown to the patient."""

    __tablename__ = "postvisit_summaries"

    id: Mapped[int] = mapped_column(primary_key=True)
    consultation_id: Mapped[int] = mapped_column(
        ForeignKey("consultations.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    patient_summary: Mapped[str] = mapped_column(Text, nullable=False)
    medication_schedule: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    follow_up_steps: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    warning_signs: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)

    consultation: Mapped[Consultation] = relationship(back_populates="postvisit_summary")


# --------------------------------------------------------------------------
# Prescriptions & medication reminders
# --------------------------------------------------------------------------
class Prescription(Base):
    __tablename__ = "prescriptions"

    id: Mapped[int] = mapped_column(primary_key=True)
    consultation_id: Mapped[int] = mapped_column(
        ForeignKey("consultations.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    patient_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    notes: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)

    consultation: Mapped[Consultation] = relationship(back_populates="prescription")
    items: Mapped[list["PrescriptionItem"]] = relationship(
        back_populates="prescription", cascade="all, delete-orphan"
    )


class PrescriptionItem(Base):
    __tablename__ = "prescription_items"
    __table_args__ = (
        CheckConstraint("frequency IN ('OD','BD','TDS','QID','QHS','SOS')", name="ck_item_frequency"),
        CheckConstraint("duration_days BETWEEN 1 AND 180", name="ck_item_duration"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    prescription_id: Mapped[int] = mapped_column(
        ForeignKey("prescriptions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    drug_name: Mapped[str] = mapped_column(String(160), nullable=False)
    dosage: Mapped[str] = mapped_column(String(80), nullable=False)  # "500 mg", "10 ml"
    frequency: Mapped[str] = mapped_column(String(8), nullable=False)
    duration_days: Mapped[int] = mapped_column(Integer, nullable=False, default=5)
    instructions: Mapped[str | None] = mapped_column(String(255))  # "after food"
    start_date: Mapped[datetime | None] = mapped_column(Date)

    prescription: Mapped[Prescription] = relationship(back_populates="items")
    reminders: Mapped[list["MedicationReminder"]] = relationship(
        back_populates="item", cascade="all, delete-orphan"
    )


class MedicationReminder(Base):
    """One scheduled dose.

    Reminders are *materialised* when the prescription is written rather than
    computed at send time. That makes the queue inspectable, lets a patient
    snooze/stop a single dose, and means the worker only ever runs one cheap
    indexed query (``status='pending' AND due_at <= now``).
    """

    __tablename__ = "medication_reminders"
    __table_args__ = (
        Index("ix_med_reminder_due", "status", "due_at"),
        UniqueConstraint("prescription_item_id", "due_at", name="uq_med_reminder_slot"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    prescription_item_id: Mapped[int] = mapped_column(
        ForeignKey("prescription_items.id", ondelete="CASCADE"), nullable=False
    )
    patient_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    due_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)
    status: Mapped[str] = mapped_column(String(16), default=JobStatus.PENDING, nullable=False)
    sent_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)

    item: Mapped[PrescriptionItem] = relationship(back_populates="reminders")


# --------------------------------------------------------------------------
# Reliability: outbox tables
# --------------------------------------------------------------------------
class Notification(Base):
    """Transactional email outbox.

    Writing the row happens **inside the same transaction** as the business
    change (booking, cancellation, …). Delivery happens later, in the worker,
    with exponential backoff. Consequences:

    * An SMTP outage can never roll back a confirmed booking.
    * A crash between "booked" and "emailed" is impossible — either both are
      committed or neither is.
    * ``idempotency_key`` is unique, so a retried request cannot double-send.
    """

    __tablename__ = "notifications"
    __table_args__ = (
        Index("ix_notifications_dispatch", "status", "next_attempt_at"),
        CheckConstraint("status IN ('pending','sent','failed','dead','cancelled')", name="ck_notification_status"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    idempotency_key: Mapped[str] = mapped_column(String(180), unique=True, nullable=False)
    template: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    to_email: Mapped[str] = mapped_column(String(255), nullable=False)
    to_name: Mapped[str | None] = mapped_column(String(160))
    subject: Mapped[str] = mapped_column(String(255), nullable=False)
    body_text: Mapped[str] = mapped_column(Text, nullable=False)
    body_html: Mapped[str | None] = mapped_column(Text)

    user_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), index=True)
    appointment_id: Mapped[int | None] = mapped_column(ForeignKey("appointments.id", ondelete="SET NULL"), index=True)

    status: Mapped[str] = mapped_column(String(16), default=JobStatus.PENDING, nullable=False)
    attempts: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    max_attempts: Mapped[int] = mapped_column(Integer, default=5, nullable=False)
    next_attempt_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)
    last_error: Mapped[str | None] = mapped_column(Text)
    provider: Mapped[str | None] = mapped_column(String(24))
    sent_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)


class CalendarTask(Base):
    """Google Calendar outbox — same reliability contract as ``Notification``."""

    __tablename__ = "calendar_tasks"
    __table_args__ = (
        Index("ix_calendar_tasks_dispatch", "status", "next_attempt_at"),
        CheckConstraint("action IN ('create','update','delete')", name="ck_calendar_action"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    idempotency_key: Mapped[str] = mapped_column(String(180), unique=True, nullable=False)
    action: Mapped[str] = mapped_column(String(12), nullable=False)
    appointment_id: Mapped[int] = mapped_column(ForeignKey("appointments.id", ondelete="CASCADE"), nullable=False, index=True)
    #: Whose calendar this touches — the patient's or the doctor's.
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    role: Mapped[str] = mapped_column(String(12), nullable=False)
    payload: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)

    status: Mapped[str] = mapped_column(String(16), default=JobStatus.PENDING, nullable=False)
    attempts: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    max_attempts: Mapped[int] = mapped_column(Integer, default=5, nullable=False)
    next_attempt_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)
    last_error: Mapped[str | None] = mapped_column(Text)
    external_event_id: Mapped[str | None] = mapped_column(String(255))
    completed_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)


class CalendarAccount(Base):
    """Stored Google OAuth 2.0 grant for one user."""

    __tablename__ = "calendar_accounts"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False)
    provider: Mapped[str] = mapped_column(String(24), default="google", nullable=False)
    google_email: Mapped[str | None] = mapped_column(String(255))
    calendar_id: Mapped[str] = mapped_column(String(255), default="primary", nullable=False)
    access_token: Mapped[str | None] = mapped_column(Text)
    refresh_token: Mapped[str | None] = mapped_column(Text)
    token_expires_at: Mapped[datetime | None] = mapped_column(UTCDateTime())
    scope: Mapped[str | None] = mapped_column(Text)
    connected_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(UTCDateTime())

    user: Mapped[User] = relationship(back_populates="calendar_account")

    @property
    def is_connected(self) -> bool:
        return bool(self.refresh_token) and self.revoked_at is None


class AuditLog(Base):
    """Append-only trail for admin-visible actions."""

    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(primary_key=True)
    actor_user_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), index=True)
    action: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    entity_type: Mapped[str] = mapped_column(String(48), nullable=False)
    entity_id: Mapped[str | None] = mapped_column(String(48))
    meta: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=utcnow, nullable=False, index=True)
